// <auto-generated />
using System;
using EfDemo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfDemo.Migrations
{
    [DbContext(typeof(DemoContext))]
    [Migration("20240204200119_RenameShareTransactionTable")]
    partial class RenameShareTransactionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("EfDemo.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("EfDemo.Share", b =>
                {
                    b.Property<int>("ShareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ShareAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("ShareId");

                    b.HasIndex("AccountId");

                    b.ToTable("Shares");
                });

            modelBuilder.Entity("EfDemo.ShareTransaction", b =>
                {
                    b.Property<int>("ShareTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BalanceChange")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShareId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ShareTransactionId");

                    b.HasIndex("ShareId");

                    b.ToTable("ShareTransactions");
                });

            modelBuilder.Entity("EfDemo.Share", b =>
                {
                    b.HasOne("EfDemo.Account", null)
                        .WithMany("Shares")
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("EfDemo.ShareTransaction", b =>
                {
                    b.HasOne("EfDemo.Share", null)
                        .WithMany("ShareTransactions")
                        .HasForeignKey("ShareId");
                });

            modelBuilder.Entity("EfDemo.Account", b =>
                {
                    b.Navigation("Shares");
                });

            modelBuilder.Entity("EfDemo.Share", b =>
                {
                    b.Navigation("ShareTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
